ungrouped:
  hosts:
    dev:
      ansible_ssh_host: 192.168.33.10
      ansible_ssh_user: vagrant
      ansible_port: 22
      ansible_ssh_private_key_file: ./varant/machines/default/virtualbox/private_key
